---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: openstack-cluster
  namespace: capi-self
spec:
  chart: openstack-cluster
  version: 0.6.0
  sourceRef:
    kind: HelmRepository
    name: capi-helm-charts
  interval: 1h
