---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets-system
spec:
  chartRef:
    kind: HelmChart
    name: sealed-secrets
  releaseName: sealed-secrets
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  driftDetection:
    mode: enabled
  interval: 10m
