---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-willt-config
  namespace: capi-self
data:
  values.yaml: |
    # Must match the name of the (sealed) secret in credentials.yaml
    cloudCredentialsSecretName: cluster-willt-credentials

    machineSSHKeyName: willt-stackhpc-com

    kubernetesVersion: 1.31.4
    machineImageId: "38797f3f-512b-42be-92a0-293e60ee4249"

    clusterNetworking:
      externalNetworkId: "ee54f79e-d33a-4866-8df0-4a4576d70243"

    controlPlane:
      machineFlavor: "ec1.medium"
      machineCount: 3

    nodeGroups:
      - name: md-0
        machineFlavor: "ec1.medium"
        machineCount: 3

    addons:
      # Use the cilium CNI
      cni:
        type: cilium

      # Enable the monitoring stack
      monitoring:
        enabled: false

      # Disable NFD and the NVIDIA/Mellanox operators
      nodeFeatureDiscovery:
        enabled: false
      nvidiaGPUOperator:
        enabled: false
      mellanoxNetworkOperator:
        enabled: false

    nodeGroupDefaults:
      kubeadmConfigSpec:
        files:
        - path: /etc/kubernetes/patches/kubeletconfiguration0+strategic.json
          owner: "root:root"
          permissions: "0644"
          content: |
            {
              "apiVersion": "kubelet.config.k8s.io/v1beta1",
              "kind": "KubeletConfiguration",
              "reservedSystemCPUs": "0",
              "topologyManagerPolicy": "restricted",
              "memoryManagerPolicy": "Static",
              "reservedMemory": [
                  {
                    "numaNode": 0,
                    "limits": {
                      "memory": "1Gi",
                    }
                  }
                ],
              "evictionHard": {
                "memory.available": "1Gi",
              },
            }
        joinConfiguration:
          nodeRegistration:
            name: '{{ local_hostname }}'
            kubeletExtraArgs:
              cloud-provider: external
          patches:
            directory: /etc/kubernetes/patches
